ICd2: ICD_STATUS_CHANGED_SIG signal sending
ICD_STATUS_CHANGED_SIG signal sending
[ICd internal functions]
Functions
static void icd_status_send_signal (const char *network_type, const char *id, const char *state_name, const char *dbus_dest, const char *uierr)
void icd_status_limited_conn (struct icd_iap *iap, const gchar *dbus_destination, const gchar *err_str)
void icd_status_connect (struct icd_iap *iap, const gchar *dbus_destination, const gchar *err_str)
void icd_status_connected (struct icd_iap *iap, const gchar *dbus_destination, const gchar *err_str)
void icd_status_disconnect (struct icd_iap *iap, const gchar *dbus_destination, const gchar *err_str)
void icd_status_disconnected (struct icd_iap *iap, const gchar *dbus_destination, const gchar *err_str)
void icd_status_scan_start (const gchar *network_type)
void icd_status_scan_stop (const gchar *network_type)
Function Documentation
void icd_status_connect (struct icd_iap * iap, const gchar * dbus_destination, const gchar * err_str)
Send a connecting signal
Parameters:
network the network to connect
dbus_destination D-Bus destination or NULL for broadcast
err_str error string or NULL if no error
References icd_iap::connection, icd_dbus_api_update_state(), ICD_STATE_CONNECTING, icd_status_send_signal(), icd_iap::id, icd_iap::id_is_local, icd_policy_request::network_id, and icd_policy_request::network_type.
Referenced by icd_osso_ic_get_state_foreach(), and icd_request_try_iap().
void icd_status_connected (struct icd_iap * iap, const gchar * dbus_destination, const gchar * err_str)
Send a connected signal
Parameters:
network the network to connect
dbus_destination D-Bus destination or NULL for broadcast
err_str error string or NULL if no error
References icd_iap::connection, icd_dbus_api_update_state(), ICD_STATE_CONNECTED, icd_status_send_signal(), icd_iap::id, icd_iap::id_is_local, icd_policy_request::network_id, and icd_policy_request::network_type.
Referenced by icd_network_api_status_update(), icd_osso_ic_get_state_foreach(), and icd_request_try_iap_cb().
void icd_status_disconnect (struct icd_iap * iap, const gchar * dbus_destination, const gchar * err_str)
Send a network disconnect signal
Parameters:
network the network to disconnect
dbus_destination D-Bus destination or NULL for broadcast
err_str error string or NULL if no error
References icd_iap::connection, icd_dbus_api_update_state(), ICD_STATE_DISCONNECTING, icd_status_send_signal(), icd_iap::id, icd_iap::id_is_local, icd_policy_request::network_id, and icd_policy_request::network_type.
Referenced by icd_network_api_close(), icd_osso_ic_get_state_foreach(), icd_request_cancel(), and icd_srv_provider_close().
void icd_status_disconnected (struct icd_iap * iap, const gchar * dbus_destination, const gchar * err_str)
Send a network disconnected signal
Parameters:
network the network to connect
dbus_destination D-Bus destination or NULL for broadcast
err_str error string or NULL if no error
References icd_iap::connection, icd_dbus_api_update_state(), ICD_STATE_DISCONNECTED, icd_status_send_signal(), icd_iap::id, icd_iap::id_is_local, icd_policy_request::network_id, and icd_policy_request::network_type.
Referenced by icd_osso_ui_retry(), and icd_request_try_iap_cb().
void icd_status_limited_conn (struct icd_iap * iap, const gchar * dbus_destination, const gchar * err_str)
Send a service provider limited network connection enabled/disabled signal
Parameters:
network the network to connect
dbus_destination D-Bus destination or NULL for broadcast
err_str error string or NULL if no error
References icd_iap::connection, icd_dbus_api_update_state(), ICD_STATE_LIMITED_CONN_DISABLED, ICD_STATE_LIMITED_CONN_ENABLED, icd_status_send_signal(), icd_iap::id, icd_iap::id_is_local, icd_iap::limited_conn, icd_policy_request::network_id, and icd_policy_request::network_type.
Referenced by icd_iap_disconnect(), icd_iap_disconnect_module(), icd_iap_module_next(), icd_osso_ic_get_state_foreach(), and icd_srv_provider_limited_conn().
void icd_status_scan_start (const gchar * network_type)
Send a scanning start signal
Parameters:
network_type network type
References icd_dbus_api_update_search(), ICD_STATE_SEARCH_START, and icd_status_send_signal().
Referenced by icd_scan_status_start().
void icd_status_scan_stop (const gchar * network_type)
Send a scanning stop signal
Parameters:
network_type network type
References icd_dbus_api_update_search(), ICD_STATE_SEARCH_STOP, and icd_status_send_signal().
Referenced by icd_scan_status_stop().
static void icd_status_send_signal (const char * network_type, const char * id, const char * state_name, const char * dbus_dest, const char * uierr) [static]
Send the actual status changed signal
Parameters:
network_type network type
network_id network id
state_name name of the state
dbus_dest D-Bus destination identifier, NULL for broadcast
uierr error string
References icd_dbus_send_system_msg(), ILOG_CRIT, and ILOG_INFO.
Referenced by icd_status_connect(), icd_status_connected(), icd_status_disconnect(), icd_status_disconnected(), icd_status_limited_conn(), icd_status_scan_start(), and icd_status_scan_stop().