ICd2: ICd context
ICd context
[ICd internal functions]
Classes
struct icd_context
Functions
gboolean icd_context_init (void)
struct icd_context * icd_context_get (void)
void icd_context_run (void)
void icd_context_stop (void)
void icd_context_destroy (void)
Variables
static struct icd_context icd_ctx
Function Documentation
void icd_context_destroy (void)
destroy context
Referenced by main().
struct icd_context * icd_context_get (void) [read]
return the global context
References icd_ctx.
Referenced by icd_dbus_api_scan_req(), icd_dbus_api_state_req(), icd_exec_signal_cb(), icd_gconf_add_notify(), icd_gconf_del_notify(), icd_iap_connect(), icd_iap_find(), icd_iap_find_by_id(), icd_iap_foreach(), icd_network_api_find_module(), icd_network_api_has_type(), icd_osso_ui_disconnect(), icd_policy_api_existing_requests_get(), icd_policy_api_run(), icd_policy_api_run_async(), icd_request_cancel(), icd_request_connect_iaps(), icd_request_foreach(), icd_request_free(), icd_request_make(), icd_request_try_iap_cb(), icd_scan_cache_remove_iap(), icd_scan_results_request(), icd_scan_results_unregister(), icd_srv_provider_check(), icd_srv_provider_connect(), icd_srv_provider_disconnect(), icd_srv_provider_identify(), and main().
gboolean icd_context_init (void)
Initialize context
References daemon, icd_ctx, main_loop, nw_module_list, and type_to_module.
Referenced by main().
void icd_context_run (void)
start the main loop
References icd_ctx, and main_loop.
Referenced by main().
void icd_context_stop (void)
stop running the main loop
References icd_ctx, and main_loop.
Referenced by icd_exec_shutdown_check().
Variable Documentation
struct icd_context icd_ctx [static]
the global ICd context
Referenced by icd_context_get(), icd_context_init(), icd_context_run(), icd_context_stop(), icd_exec_shutdown_check(), icd_exec_signal_cb(), icd_gconf_add_notify(), icd_gconf_del_notify(), icd_iap_connect(), icd_iap_find(), icd_iap_find_by_id(), icd_iap_foreach(), icd_network_api_find_module(), icd_network_api_has_type(), icd_network_api_init_cb(), icd_osso_ui_disconnect(), icd_policy_api_existing_requests_get(), icd_policy_api_init_cb(), icd_policy_api_run(), icd_policy_api_run_async(), icd_request_cancel(), icd_request_connect_iaps(), icd_request_foreach(), icd_request_free(), icd_request_make(), icd_request_try_iap_cb(), icd_scan_cache_remove_iap(), icd_scan_results_request(), icd_scan_results_unregister(), icd_srv_provider_check(), icd_srv_provider_connect(), icd_srv_provider_disconnect(), and icd_srv_provider_identify().