ICd2: Testing module for the network api
Testing module for the network api
[Testing componenets]
Classes
struct test_module_struct
Enumerations
enum test_module_state { TEST_MODULE_IDLING, TEST_MODULE_SCANNING, TEST_MODULE_FAKING_ACTIVE }
Functions
static gboolean test_report_scan (gpointer data)
static gboolean test_ip_up_callback (gpointer data)
static void test_ip_up (const gchar *network_type, const guint network_attrs, const gchar *network_id, const gchar *interface_name, icd_nw_ip_up_cb_fn ip_up_cb, const gpointer ip_up_cb_token, gpointer *private)
static gboolean test_link_post_up_callback (gpointer data)
static void test_link_post_up (const gchar *network_type, const guint network_attrs, const gchar *network_id, const gchar *interface_name, icd_nw_link_post_up_cb_fn link_post_up_cb, const gpointer link_post_up_cb_token, gpointer *private)
static gboolean test_link_up_callback (gpointer data)
static void test_link_up (const gchar *network_type, const guint network_attrs, const gchar *network_id, icd_nw_link_up_cb_fn link_up_cb, const gpointer link_up_cb_token, gpointer *private)
gboolean icd_nw_init (struct icd_nw_api *network_api, icd_nw_watch_pid_fn watch_cb, gpointer watch_cb_token, icd_nw_close_fn close_cb, gpointer close_cb_token)
Variables
static gchar * test_type [2]
static gchar test_name [4]
static gchar test_id [4]
Enumeration Type Documentation
enum test_module_state
the internal status for the test module
Enumerator:
TEST_MODULE_IDLING idling
TEST_MODULE_SCANNING scanning
TEST_MODULE_FAKING_ACTIVE active
Function Documentation
gboolean icd_nw_init (struct icd_nw_api * network_api, icd_nw_watch_pid_fn watch_cb, gpointer watch_cb_token, icd_nw_close_fn close_cb, gpointer close_cb_token)
Initialize testing module
Parameters:
network_api the api to fill in
watch_cb function to inform ICd that a child process is to be monitored for exit status
watch_cb_token token to pass to the watch pid function
close_cb function to inform ICd that the network connection is to be closed
close_cb_token token to pass to the close function
Returns:
TRUE
References ILOG_DEBUG, icd_nw_api::ip_up, icd_nw_api::link_post_up, icd_nw_api::link_up, icd_nw_api::network_destruct, icd_nw_api::private, icd_nw_api::search_interval, icd_nw_api::search_lifetime, icd_nw_api::start_search, icd_nw_api::stop_search, test_ip_up(), test_link_post_up(), and test_link_up().
static void test_ip_up (const gchar * network_type, const guint network_attrs, const gchar * network_id, const gchar * interface_name, icd_nw_ip_up_cb_fn ip_up_cb, const gpointer ip_up_cb_token, gpointer * private) [static]
Fake ip_up function
Parameters:
network_type network type
network_attrs attributes
network_id IAP name or local id, e.g. SSID
interface_name name of the interface
ip_up_cb the callback function to call when the link is up
ip_up_cb_token token to pass to the callback function
private a reference to the icd_nw_api private member
References ICD_NW_SUCCESS, ILOG_CRIT, ILOG_DEBUG, test_module_struct::status, and test_ip_up_callback().
Referenced by icd_nw_init().
static gboolean test_ip_up_callback (gpointer data) [static]
Timeout callback for the ip_up function
Parameters:
data test structure
Returns:
FALSE
References ILOG_DEBUG.
Referenced by test_ip_up().
static void test_link_post_up (const gchar * network_type, const guint network_attrs, const gchar * network_id, const gchar * interface_name, icd_nw_link_post_up_cb_fn link_post_up_cb, const gpointer link_post_up_cb_token, gpointer * private) [static]
Fake link_post_up function
Parameters:
network_type network type
network_attrs attributes
network_id IAP name or local id, e.g. SSID
interface_name name of the interface
link_post_up_cb the callback function to call when the link is up
link_post_up_cb_token token to pass to the callback function
private a reference to the icd_nw_api private member
References ICD_NW_SUCCESS, ILOG_CRIT, ILOG_DEBUG, test_module_struct::status, and test_link_post_up_callback().
Referenced by icd_nw_init().
static gboolean test_link_post_up_callback (gpointer data) [static]
Timeout callback for the link_post_up function
Parameters:
data test structure
Returns:
FALSE
References ILOG_DEBUG.
Referenced by test_link_post_up().
static void test_link_up (const gchar * network_type, const guint network_attrs, const gchar * network_id, icd_nw_link_up_cb_fn link_up_cb, const gpointer link_up_cb_token, gpointer * private) [static]
Fake link_up function
Parameters:
network_type network type
network_attrs attributes
network_id IAP name or local id, e.g. SSID
link_up_cb the callback function to call when the link is up
link_up_cb_token token to pass to the callback function
private a reference to the icd_nw_api private member
References ICD_NW_LEVEL_NONE, ICD_NW_SEARCH_COMPLETE, ICD_NW_SUCCESS, ILOG_CRIT, ILOG_DEBUG, test_module_struct::status, test_link_up_callback(), and TEST_MODULE_FAKING_ACTIVE.
Referenced by icd_nw_init().
static gboolean test_link_up_callback (gpointer data) [static]
Timeout callback for the link_up function
Parameters:
data test structure
Returns:
FALSE
References ILOG_DEBUG.
Referenced by test_link_up().
static gboolean test_report_scan (gpointer data) [static]
Callback for the search function.
Parameters:
data private data
Returns:
TRUE to continue sending reports, FALSE to stop
References ICD_NW_LEVEL_NONE, ICD_NW_SEARCH_COMPLETE, ICD_NW_SEARCH_CONTINUE, ILOG_CRIT, test_module_struct::status, test_id, TEST_MODULE_IDLING, test_name, and test_type.
Variable Documentation
gchar test_id[4] [static]
dummy network id
Referenced by test_report_scan().
gchar test_name[4] [static]
dummy network name
Referenced by test_report_scan().
gchar* test_type[2] [static]
Initial value:
 {
  "TEST",
  "TEST_TYPE_2"
}
dummy network types
Referenced by test_report_scan().