ICd2: Defines for WLAN attribute bits
Defines for WLAN attribute bits
[ICd internal functions]
Defines
#define WLAN_TYPE_INFRA "WLAN_INFRA"
#define WLAN_TYPE_ADHOC "WLAN_ADHOC"
#define WLAN_SECURITY_OPEN 0x1 << 3
#define WLAN_SECURITY_WEP 0x2 << 3
#define WLAN_SECURITY_WPA_PSK 0x4 << 3
Functions
guint icd_wlan_defs_get_secmode (const gchar *iap_name)
gboolean icd_wlan_defs_is_wlan (const gchar *network_type)
Detailed Description
Todo:
Remove this file when wlan provides a .h file with the needed defines
Define Documentation
#define WLAN_SECURITY_OPEN 0x1 << 3
open wlan network setting in network attributes
#define WLAN_SECURITY_WEP 0x2 << 3
wep wlan encryption in netowork attributes
Referenced by icd_wlan_defs_get_secmode().
#define WLAN_SECURITY_WPA_PSK 0x4 << 3
wpa psk wlan encryption in network attributes
#define WLAN_TYPE_ADHOC "WLAN_ADHOC"
wlan ad-hoc mode
#define WLAN_TYPE_INFRA "WLAN_INFRA"
wlan infrastructure mode
Function Documentation
guint icd_wlan_defs_get_secmode (const gchar * iap_name)
Get wlan security attributes for an IAP
Parameters:
iap_name IAP name
Returns:
wlan security network attributes
References icd_gconf_get_iap_string(), and WLAN_SECURITY_WEP.
Referenced by icd_osso_ic_make_request().
gboolean icd_wlan_defs_is_wlan (const gchar * network_type)
Check wheter the network type is wlan
Parameters:
network_type network type
Returns:
TRUE if wlan, FALSE otherwise
Referenced by icd_osso_ic_make_request().