ICd2: ICd execution
ICd execution
[ICd internal functions]
Defines
#define PIDFILE "/var/run/icd2.pid"
#define ICD_SHUTDOWN_TIMEOUT 100
Enumerations
enum icd_exit_status {
EXIT_FORK_FAILED = 2, EXIT_SETSID_FAILED, EXIT_FILE_OPEN_FAILED, EXIT_DUP_FAILED,
EXIT_DBUS_ERROR, EXIT_REGISTER_ERROR, EXIT_GCONF_ERROR, EXIT_SOCKETPAIR_FAILED,
EXIT_SIGNAL_HANDLERS_FAILED, EXIT_WATCH_FAILED, EXIT_ANOTHER_INSTANCE_RUNNING, EXIT_FAILED_TO_INIT,
EXIT_PID_WRITE_FAILED
}
Functions
static gboolean icd_exec_shutdown_check (struct icd_context *icd_ctx)
static void icd_exec_shutdown (struct icd_context *icd_ctx)
static void icd_exec_signal_cb (int sig)
int main (int argc, char *argv[])
Define Documentation
#define ICD_SHUTDOWN_TIMEOUT 100
shutdown timeout function interval in ms
Referenced by icd_exec_shutdown().
#define PIDFILE "/var/run/icd2.pid"
the pid file identical to previous version of icd
Referenced by main().
Enumeration Type Documentation
enum icd_exit_status
exit status
Function Documentation
static void icd_exec_shutdown (struct icd_context * icd_ctx) [static]
Cancel all requests and shut down ICd
Parameters:
icd_ctx icd context
References icd_dbus_api_deinit(), icd_exec_shutdown_check(), icd_osso_ic_deinit(), ICD_POLICY_ATTRIBUTE_CONN_UI, icd_request_cancel(), ICD_SHUTDOWN_TIMEOUT, ILOG_DEBUG, ILOG_ERR, ILOG_INFO, icd_context::request_list, and icd_context::shutting_down.
Referenced by icd_exec_signal_cb().
static gboolean icd_exec_shutdown_check (struct icd_context * icd_ctx) [static]
Wait until the last request has exited and quit ICd
Parameters:
icd_ctx icd context
Returns:
TRUE while waiting, FALSE when all requests have been removed
References icd_context_stop(), icd_ctx, ILOG_DEBUG, ILOG_INFO, and icd_context::request_list.
Referenced by icd_exec_shutdown().
static void icd_exec_signal_cb (int sig) [static]
Callback to handle posix signals
Parameters:
sig signal received
References icd_context_get(), icd_ctx, icd_exec_shutdown(), icd_log_nextlevel(), icd_network_api_notify_pid(), icd_script_notify_pid(), icd_srv_provider_notify_pid(), ILOG_DEBUG, ILOG_INFO, and ILOG_WARN.
Referenced by main().
int main (int argc, char * argv[])
Main function
Parameters:
argc argc
argv argv
Returns:
0 normal termination, >0 on error
References icd_context::daemon, icd_args_decode(), icd_context_destroy(), icd_context_get(), icd_context_init(), icd_context_run(), icd_dbus_api_init(), icd_exec_signal_cb(), icd_gconf_add_notify(), icd_gconf_del_notify(), icd_gconf_remove_temporary(), icd_idle_timer_init(), icd_idle_timer_remove(), icd_log_close(), icd_log_open(), icd_name_owner_init(), icd_network_api_load_modules(), icd_network_api_unload_modules(), icd_network_priority_pref_init(), icd_osso_ic_init(), icd_pid_check(), icd_pid_remove(), icd_pid_write(), icd_policy_api_load_modules(), icd_policy_api_unload_modules(), icd_signal_init(), icd_srv_provider_load_modules(), icd_srv_provider_unload_modules(), ILOG_ERR, ILOG_INFO, and PIDFILE.