ICd2: D-Bus NameOwnerChanged message handling
D-Bus NameOwnerChanged message handling
[ICd internal functions]
Defines
#define ICD_NAME_OWNER_FILTER_STRING "member='NameOwnerChanged',arg0='%s'"
Functions
static DBusHandlerResult icd_name_owner_filter (DBusConnection *connection, DBusMessage *message, void *user_data)
gboolean icd_name_owner_remove_filter (const gchar *application)
gboolean icd_name_owner_add_filter (const gchar *application)
gboolean icd_name_owner_init (struct icd_context *icd_ctx)
Function Documentation
gboolean icd_name_owner_add_filter (const gchar * application)
Add a filter for NameOwnerChanged signals for a specific application
Parameters:
application application D-Bus id
Returns:
the return status of icd_dbus_connect_system_bcast_signal
References icd_dbus_connect_system_bcast_signal(), and icd_name_owner_filter().
Referenced by icd_dbus_api_scan_req(), icd_name_owner_init(), and icd_request_tracking_info_add().
static DBusHandlerResult icd_name_owner_filter (DBusConnection * connection, DBusMessage * message, void * user_data) [static]
D-Bus filter function for NameOwnerChanged messages
Parameters:
connection D-Bus system bus
message D-Bus message
user_data icd context
Returns:
DBUS_HANDLER_RESULT_NOT_YET_HANDLED if error, DBUS_HANDLER_RESULT_HANDLED otherwise
References icd_dbus_api_app_exit(), ICD_POLICY_ATTRIBUTE_CONN_UI, icd_request_cancel(), icd_request_find(), icd_request_tracking_info_delete(), icd_tracking_info_find(), icd_tracking_info_update(), ILOG_INFO, and ILOG_WARN.
Referenced by icd_name_owner_add_filter(), and icd_name_owner_remove_filter().
gboolean icd_name_owner_init (struct icd_context * icd_ctx)
Initialize NameOwnerChanged filtering
Parameters:
icd_ctx icd context
Returns:
TRUE on success, FALSE on failure
References icd_name_owner_add_filter().
Referenced by main().
gboolean icd_name_owner_remove_filter (const gchar * application)
Remove a filter for NameOwnerChanged signals for a specific application
Parameters:
application application D-Bus id
Returns:
the return status of icd_dbus_disconnect_system_bcast_signal
References icd_dbus_disconnect_system_bcast_signal(), and icd_name_owner_filter().
Referenced by icd_dbus_api_app_exit(), and icd_request_tracking_info_delete_foreach().